name: ImageOnMap
main: fr.moribus.ImageOnMap.ImageOnMap
version: 1.2.2

commands:
   tomap:
      description: render an image in a map
      usage: /<command> [URL]
   rmmap:
      description: remove an image
      usage: /<command>
      
permissions:
    imageonmap.userender:
        description: Allows you to use /tomap
        default: op