name: ImageOnMap
main: fr.moribus.ImageOnMap.ImageOnMap
version: 2.5.1

commands:
   tomap:
      description: render an image in a map
      usage: /<command> [URL]
   maptool:
      description: manage maps
      usage: /<command>
      
permissions:
    imageonmap.userender:
        description: Allows you to use /tomap
        default: op