name: ImageOnMap
main: fr.moribus.imageonmap.ImageOnMap
version: 2.99

commands:
   tomap:
      description: render an image in a map
      usage: /<command> [URL]
   maptool:
      description: manage maps
   maptool-migration:
      description: Manages the ImageOnMap migrations
      permission: op
permissions:
    imageonmap.userender:
        description: Allows you to use /tomap
        default: op